language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: BF21rtzlr9zm9u7/r0qeK37zRWdQs6poppvGKyKf0rloeZe4ymChKVQI9pQnWeaTxEE/60q70FLhumex6mkK9t5tJKT6tQTOncRoPh+rJazWa2lCRbshqZGw2prBasYKXsYPQY9I06FVV/aeOIpXJ3jYX1g3n0dkbmEzKBlZhCEbp9WlygD7xOc/ELfsTILSbmfNBRYsUyIutw+u5qxQrPUPJeVsbuuXgTTpAJ7XUtOxGJvb5/kVzNVojTfLwFBDIcBSB1v4TorEAL8el1uAI43fgejCS/E7kLBc7RQ6MFqYfdcsMTkzEgLdOkrVevos3PqnMUCqy3DO24fzCafSvKuVN71e7+YsfndJuwqj08uw6ekgYcw42ALUKhcFiGdZk9v5WKCMN9zGI4zdqJpVEYZML4JmGUG6yrSFqfFORy56wmUXKwHN8a4/WC0T9M5uIJ6db3gDbCdWpzkZAdCd83sqa3RLlss4hX/A7KaPG/79ZpN8FtuiF5WcK6AaXGmi7kGR5iqCjBB19m73ugfVkHPJOYzaJy1l3kRLeCtuh8Mf4dvNWUbhnLdFH6N1cTPf4l4pDTcZFvc4APwil7DAuCy30Pj5OTbeZL6UM2NkWvM1mVUj5a8b3F+RJzUGirj6BT5hQEakBvQw0zpTpVlwoFVFP0p3/839Wu4DBVuhU0Y=
  file:
    - "remark-man.js"
    - "remark-man.min.js"
  on:
    tags: true
    node: '9.0'
